---
abstract: 'Set default of an attribute to a value from %ENV'
author:
  - 'John Napiorkowski <jjnapiork@cpan.org>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.72'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: MooseX-Attribute-ENV
no_index:
  directory:
    - inc
    - t
requires:
  Moose: 0.48
  perl: 5.8.6
version: 0.01
